### PR TITLE
Solve "UnicodeDecodeError: 'utf-8' codec can't decode byte 0x95 ..."

### PR DESCRIPTION
**Pull request by sangkaka**
Solve "UnicodeDecodeError: 'utf-8' codec can't decode byte 0x95 in position 0: invalid start byte"

### CODE REVIEW

**Comment by sangkaka** [comment]
_name:
b'\x95\xd4\x95i\x8a\xf3~1.XLS\x00'

**Comment by nathan30** [comment]
@koodaamo will you merge this one day ?

**Comment by petri** [comment]
@sangkaka / @nathan30 can you provide a bit more context for the problem, and a file that demonstrates a problem with current code? An issue would help get this merged, and a test even more so.

**Comment by nathan30** [comment]
@petri The OP provice a name example, this is enough to reproduce the error. Badly, I can't provide a TNF file, as the bad ones contains private informations..

For now I do that to avoid error when accessing name var : 

```
encoding = chardet.detect(att._name)['encoding']
filename = str(att._name, encoding=encoding).strip('\x00')
```

**Pull request merged**
