### PR TITLE
fixes & enhancements in parsing

### PR DESCRIPTION
**Pull request by emdete**
i added the parsing of datatypes in tnef and fixed some bugs in tnef parsing

### CODE REVIEW

**Comment by petri** [comment]
Thank you for the pull request. My apologies for not handling the PR in due time.

However, the PR is quite large. I would like to handle the different kinds of changes you're proposing in different PRs. Would that be ok?

With that in mind, could you first make a separate PR for the parsing of datatypes? Same goes for clear bugs that you have found. I will try & merge those ASAP.

I am not against beautifying the API & optimizations etc. but would like to handle those separately.

**Comment by emdete** [comment]
as some patches depend on each other it will be difficult... i would suggest to take it as is to prevent unessesary work (time is short). if in doubt just use cherrypick to take the changes that you want.

**Comment by petri** [comment]
@jrideout are there any improvements here that you'd be interested in taking a look at? I am thinking especially e1a6340, d3c6ebc, 6c91519 and 6fb7579 that promise fixes and enhancements.

**Comment by jrideout** [comment]
@petri After #38, I think we accounted for all the changes in this PR

**Pull request closed without merging**
